/*
 * glcd_defines.h
 *
 *  Created on: May 25, 2025
 *      Author: krisz
 */

#ifndef LCD_GLCD_DEFINES_H_
#define LCD_GLCD_DEFINES_H_

#define GLCD_DI_DATA_MODE GPIO_PIN_SET
#define GLCD_DI_COMMAND_MODE GPIO_PIN_RESET

#define GLCD_EMPTY_BYTE 0xFF

#define GLCD_TURN_ON 0x3F
#define GLCD_Y_ADDR_ZERO 0x40
#define GLCD_X_ADDR_ZERO 0xB8
#define GLCD_Z_ADDR_ZERO 0xC0

#define SCORE_TXT_HEIGHT 9
#define SCORE_TXT_WIDTH 40
#define SCORE_TXT_BLOCKS (SCORE_TXT_WIDTH / 8)

#define GAME_AREA_START_COL 9
#define GAME_AREA_END_COL GLCD_COLS
#define BLOCK_WIDTH 8

#define GLCD_ROWS 64
#define GLCD_COLS 128

#define GLCD_BLOCK_HEIGHT 20
#define GLCD_BLOCK_WIDTH 38
#define GLCD_BLOCK_RIGHT_MARGIN 13
#define GLCD_OUTLINE_WIDTH 1
#define GLCD_WINDOW_HEIGHT 10
#define GLCD_WINDOW_WIDTH 9
#define GLCD_WINDOW_VERTICAL_LINE_HEIGHT GLCD_WINDOW_HEIGHT
#define GLCD_WINDOW_HORIZONTAL_LINE_WIDTH GLCD_WINDOW_WIDTH
#define GLCD_LEFT_WINDOW_MARGIN_FROM_BORDER 6
#define GLCD_SPACING_BETWEEN_WINDOWS 8

#endif /* LCD_GLCD_DEFINES_H_ */
